name: splineopt
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - pillow
  - scipy
  - tk
  - pyqtgraph
  - pyqt5
  - pip
  - pip:
      - pyqt5-tools
      - torchaudio==2.6.0+cu118
      - torchvision==0.21.0+cu118
